### ISSUE TITLE
F1 tracks unavailable?

### ISSUE THREAD

**Issue by tsigalko18** [robotics-masters/sim-donkeycar-f1#1]
Hello, I failed to identify the scenes/prefab with the F1 tracks in all branches. Are they not yet available?

**Comment by wallarug** [comment]
Hey there @tsigalko18 ,

They are not published yet.  I am in the process of tidying them up so they work in this repository.  

There was 7 teams working on 14 tracks.  There's quite a bit to clean up.  The other challenge is they are using the older version of the simulator (before the refactoring).

Please give me a little bit more time to get them up.

**Comment by wallarug** [comment]
Hi again,

I am slowly adding them.  No guarantees that any will work out of the box, but you can follow the progress here:

https://github.com/robotics-masters/sim-donkeycar-f1/tree/f1-tracks

**Comment by tsigalko18** [comment]
ok, no rush, thanks for the fast reply :) 
Nice to see this project going! 

Will start testing w/ the tracks you've added
